project: "thermoMPNN_minimal"
name: "fireprot_weights_training"
logger: "csv"

platform:
  accel: "gpu"
  cache_dir: "cache"
  thermompnn_dir: "./inference"

datasets: "fireprot"

data_loc:
  weights_dir: "./weights"
  torch_hub: "./esm_models"

training:
  num_workers: 8
  learn_rate: 0.001
  epochs: 100
  lr_schedule: true
  mpnn_learn_rate: 0.001
  two_stage: false
  testing: true
  ddp: false
  add_esm_embeddings: false
  esm_model: "esm2_t33_650M_UR50D"
  reweighting: false
  weight_method: "weight_lds_inverse"
  seed: 0

model:
  hidden_dims: [64, 32]
  subtract_mut: false
  num_final_layers: 3
  freeze_weights: true
  load_pretrained: true
  lightattn: true
